<a href="https://colab.research.google.com/github/GIGAREHAN/Pytorch/blob/main/Training_pipeline_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [7]:
X_train, X_test

(     radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
 326       14.110         12.88           90.03      616.5          0.09309
 330       16.030         15.51          105.80      793.2          0.09491
 274       17.930         24.48          115.20      998.9          0.08855
 456       11.630         29.29           74.87      415.1          0.09357
 97         9.787         19.94           62.11      294.5          0.10240
 ..           ...           ...             ...        ...              ...
 554       12.880         28.92           82.50      514.3          0.08123
 259       15.530         33.56          103.70      744.9          0.10630
 542       14.740         25.42           94.70      668.6          0.08275
 295       13.770         13.27           88.06      582.7          0.09198
 112       14.260         19.65           97.83      629.9          0.07837

      compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
 326           0.05306        0.017650             0.027330         0.1373
 330           0.13710        0.120400             0.070410         0.1782
 274           0.07027        0.056990             0.047440         0.1538
 456           0.08574        0.071600             0.020170         0.1799
 97            0.05301        0.006829             0.007937         0.1350
 ..                ...             ...                  ...            ...
 554           0.05824        0.061950             0.023430         0.1566
 259           0.16390        0.175100             0.083990         0.2091
 542           0.07214        0.041050             0.030270         0.1840
 295           0.06221        0.010630             0.019170         0.1592
 112           0.22330        0.300300             0.077980         0.1704

      fractal_dimension_mean  ...  radius_worst  texture_worst  \
 326                 0.05700  ...         15.53          18.00
 330                 0.05976  ...         18.76          21.98
 274                 0.05510  ...         20.92          34.69
 456                 0.06166  ...         13.12          38.81
 97                  0.06890  ...         10.92          26.29
 ..                      ...  ...           ...            ...
 554                 0.05708  ...         13.89          35.74
 259                 0.06650  ...         18.49          49.54
 542                 0.05680  ...         16.51          32.29
 295                 0.05912  ...         14.67          16.93
 112                 0.07769  ...         15.30          23.73

      perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
 326            98.40       749.9           0.12810            0.11090
 330           124.30      1070.0           0.14350            0.44780
 274           135.10      1320.0           0.13150            0.18060
 456            86.04       527.8           0.14060            0.20310
 97             68.81       366.1           0.13160            0.09473
 ..               ...         ...               ...                ...
 554            88.84       595.7           0.12270            0.16200
 259           126.30      1035.0           0.18830            0.55640
 542           107.40       826.4           0.10600            0.13760
 295            94.17       661.1           0.11700            0.10720
 112           107.00       709.0           0.08949            0.41930

      concavity_worst  concave points_worst  symmetry_worst  \
 326          0.05307               0.05890          0.2100
 330          0.49560               0.19810          0.3019
 274          0.20800               0.11360          0.2504
 456          0.29230               0.06835          0.2884
 97           0.02049               0.02381          0.1934
 ..               ...                   ...             ...
 554          0.24390               0.06493          0.2372
 259          0.57030               0.20140          0.3512
 542          0.16110               0.10950          0.2722
 295          0.03732               0.05802          0.2823
 112          0.67830               0.15050          0.2398

      fractal_dimension_worst
 326                  0.07083
 330                  0.09124
 274                  0.07948
 456                  0.07220
 97                   0.08988
 ..                       ...
 554                  0.07242
 259                  0.12040
 542                  0.06956
 295                  0.06794
 112                  0.10820

 [455 rows x 30 columns],
      radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
 433        18.82         21.97          123.70     1110.0          0.10180
 154        13.15         15.34           85.31      538.9          0.09384
 325        12.67         17.30           81.25      489.9          0.10280
 53         18.22         18.70          120.30     1033.0          0.11480
 339        23.51         24.27          155.10     1747.0          0.10690
 ..           ...           ...             ...        ...              ...
 272        21.75         20.99          147.30     1491.0          0.09401
 380        11.27         12.96           73.16      386.3          0.12370
 348        11.47         16.03           73.02      402.7          0.09076
 449        21.10         20.52          138.10     1384.0          0.09684
 436        12.87         19.54           82.67      509.2          0.09136

      compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
 433           0.13890         0.15940              0.08744         0.1943
 154           0.08498         0.09293              0.03483         0.1822
 325           0.07664         0.03193              0.02107         0.1707
 53            0.14850         0.17720              0.10600         0.2092
 339           0.12830         0.23080              0.14100         0.1797
 ..                ...             ...                  ...            ...
 272           0.19610         0.21950              0.10880         0.1721
 380           0.11110         0.07900              0.05550         0.2018
 348           0.05886         0.02587              0.02322         0.1634
 449           0.11750         0.15720              0.11550         0.1554
 436           0.07883         0.01797              0.02090         0.1861

      fractal_dimension_mean  ...  radius_worst  texture_worst  \
 433                 0.06132  ...         22.66          30.93
 154                 0.06207  ...         14.77          20.50
 325                 0.05984  ...         13.71          21.10
 53                  0.06310  ...         20.60          24.13
 339                 0.05506  ...         30.67          30.73
 ..                      ...  ...           ...            ...
 272                 0.06194  ...         28.19          28.18
 380                 0.06914  ...         12.84          20.53
 348                 0.06372  ...         12.51          20.79
 449                 0.05661  ...         25.68          32.07
 436                 0.06347  ...         14.45          24.38

      perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
 433           145.30      1603.0            0.1390             0.3463
 154            97.67       677.3            0.1478             0.2256
 325            88.70       574.4            0.1384             0.1212
 53            135.10      1321.0            0.1280             0.2297
 339           202.40      2906.0            0.1515             0.2678
 ..               ...         ...               ...                ...
 272           195.90      2384.0            0.1272             0.4725
 380            84.93       476.1            0.1610             0.2429
 348            79.67       475.8            0.1531             0.1120
 449           168.20      2022.0            0.1368             0.3101
 436            95.14       626.9            0.1214             0.1652

      concavity_worst  concave points_worst  symmetry_worst  \
 433          0.39120               0.17080          0.3007
 154          0.30090               0.09722          0.3849
 325          0.10200               0.05602          0.2688
 53           0.26230               0.13250          0.3021
 339          0.48190               0.20890          0.2593
 ..               ...                   ...             ...
 272          0.58070               0.18410          0.2833
 380          0.22470               0.13180          0.3343
 348          0.09823               0.06548          0.2851
 449          0.43990               0.22800          0.2268
 436          0.07127               0.06384          0.3313

      fractal_dimension_worst
 433                  0.08314
 154                  0.08633
 325                  0.06888
 53                   0.07987
 339                  0.07738
 ..                       ...
 272                  0.08858
 380                  0.09215
 348                  0.08763
 449                  0.07425
 436                  0.07735

 [114 rows x 30 columns])

#Scaling

In [10]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(

In [11]:
X_train, X_test

(array([[-0.02037918, -1.45143959, -0.09424737, ..., -0.84519317,
         -1.32853457, -0.72093326],
        [ 0.52055585, -0.86333957,  0.5500225 , ...,  1.26466084,
          0.20324586,  0.42439317],
        [ 1.05585615,  1.14246163,  0.93405147, ..., -0.01610543,
         -0.65515122, -0.23553034],
        ...,
        [ 0.15711513,  1.35265707,  0.09654149, ..., -0.07824911,
         -0.2917909 , -0.79220051],
        [-0.11616976, -1.36423084, -0.17473004, ..., -0.85853133,
         -0.12344507, -0.88310834],
        [ 0.02188137,  0.06241483,  0.22441496, ...,  0.54318777,
         -0.83183101,  1.3761196 ]]),
 array([[1.882e+01, 2.197e+01, 1.237e+02, ..., 1.708e-01, 3.007e-01,
         8.314e-02],
        [1.315e+01, 1.534e+01, 8.531e+01, ..., 9.722e-02, 3.849e-01,
         8.633e-02],
        [1.267e+01, 1.730e+01, 8.125e+01, ..., 5.602e-02, 2.688e-01,
         6.888e-02],
        ...,
        [1.147e+01, 1.603e+01, 7.302e+01, ..., 6.548e-02, 2.851e-01,
         8.763e-02],
        [2.110e+01, 2.052e+01, 1.381e+02, ..., 2.280e-01, 2.268e-01,
         7.425e-02],
        [1.287e+01, 1.954e+01, 8.267e+01, ..., 6.384e-02, 3.313e-01,
         7.735e-02]]))

In [13]:
y_train.head()

326    B
330    M
274    M
456    B
97     B
Name: diagnosis, dtype: object

#Label Encoder

In [14]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [15]:
y_train

array([0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0])

#Numpy arrays to Pytroch Tensors

In [16]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [17]:
X_train_tensor.shape

torch.Size([455, 30])

In [18]:
y_train_tensor.shape

torch.Size([455])

#Defining the model

In [37]:
import torch.nn as nn

class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)
    return out

In [38]:
learning_rate = 0.1
epochs = 25

In [39]:
loss_function = nn.BCELoss()

In [40]:
model = MySimpleNN(X_train_tensor.shape[1])

optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

for epoch in range(epochs):

  #forward pass
  y_pred = model(X_train_tensor)

  #loss
  loss = loss_function(y_pred, y_train_tensor.unsqueeze(1))

  #clear grad
  optimizer.zero_grad()

  #backward pass
  loss.backward()

  #parameters update
  optimizer.step()

  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.5552831888198853
Epoch: 2, Loss: 0.4521806538105011
Epoch: 3, Loss: 0.38972756266593933
Epoch: 4, Loss: 0.3477415442466736
Epoch: 5, Loss: 0.3173833191394806
Epoch: 6, Loss: 0.29425403475761414
Epoch: 7, Loss: 0.27592918276786804
Epoch: 8, Loss: 0.26096540689468384
Epoch: 9, Loss: 0.24845057725906372
Epoch: 10, Loss: 0.23778021335601807
Epoch: 11, Loss: 0.22853755950927734
Epoch: 12, Loss: 0.22042584419250488
Epoch: 13, Loss: 0.21322786808013916
Epoch: 14, Loss: 0.2067805677652359
Epoch: 15, Loss: 0.20095926523208618
Epoch: 16, Loss: 0.19566677510738373
Epoch: 17, Loss: 0.19082598388195038
Epoch: 18, Loss: 0.18637500703334808
Epoch: 19, Loss: 0.18226347863674164
Epoch: 20, Loss: 0.1784498244524002
Epoch: 21, Loss: 0.17489953339099884
Epoch: 22, Loss: 0.17158347368240356
Epoch: 23, Loss: 0.16847701370716095
Epoch: 24, Loss: 0.1655590832233429
Epoch: 25, Loss: 0.1628115028142929

In [41]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.3684210479259491